### ISSUE TITLE
TypeError: doconn() got an unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by A-Nicoladie** [sairuk/litch#1]
Hi and thanks for this script!

I have an error when I try `--claim-bundles`

`$ ./litch.py --login`  
> litch 0.1alpha
> 
> Login process starting, prepare to login
> 
> Email Address: xxxxxxxxxxxxxxx
> Password: 
> [INFO] Login successful
> [INFO] Handling MFA
> Enter MFA code: xxxxxxxxxxxx
> [INFO] MFA was successful

`$ ./litch.py --claim-bundles`  
> [INFO] Loading Bundles
> [INFO] Reading page https://itch.io/my-purchases/bundles
> [INFO] Found 1 bundles
> [INFO] Switching bundles
> [INFO] Switching to page 1
> [INFO] Found 0 unclaimed items
> [INFO] Switching to page 2
> [INFO] Found 0 unclaimed items
> [INFO] Switching to page 3
> [INFO] Found 13 unclaimed items
> [INFO] Starting claim process
> [INFO] Claiming game_id: 465154
> Traceback (most recent call last):
>   File "./litch.py", line 516, in <module>
>     main(args)
>   File "./litch.py", line 484, in main
>     bundles()
>   File "./litch.py", line 216, in bundles
>     doconn(burl, conn_type="POST", data=payload, headers=headers)
> TypeError: doconn() got an unexpected keyword argument 'data'

I'm not an python dev, but I try to change  
`doconn(burl, conn_type="POST", data=payload, headers=headers)`  
by this  
`doconn(client, burl, conn_type="POST", payload=payload, headers=headers)`  
and it worked

**Comment by sairuk** [comment]
thanks for letting me know, oversight on my part. thanks for the pull request also, have merged.
